apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo-k8s
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo-k8s
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo-k8s
        tier: frontend
    spec:
      containers:
      - name: demo-k8s
        image: abhishekdarapu/demo-k8s:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s
  namespace: default
spec:
  selector:
    app: demo-k8s
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
